### ISSUE TITLE
What should we do with the exceptions thrown in ParseZIP.stringVectorToTrade

### ISSUE THREAD

**Issue by sztankatt** [CSTIB-Hotel/OTCAnalyser#12]
Currently they are being catched in the ParseZIP.downloadData, which means, that only valid rows will be included in the database. We could for example keep track, ie count the number of failed/successful rows. 

@seansaville @weiszg @lmp47 @alistairfisher @waiwaing

**Comment by seansaville** [comment]
Maybe this is something to think about for the next iteration, after we've got a working prototype to show the client :) I think for now it's best that only valid rows get stored in the database
