### ISSUE TITLE
Very old trades appearing in the database

### ISSUE THREAD

**Issue by seansaville** [CSTIB-Hotel/OTCAnalyser#16]
As above - this is an issue lots of us have been seeing, but no idea why. @waiwaing has suggested we explicitly flag UPDATEs in the database in order to see if these are just updates to very old, long-standing trades or some kind of error.

**Comment by weiszg** [comment]
we have to check this again tomorrow, there's a major bug fix in the hacky branch now that *might* solve it

**Comment by waiwaing** [comment]
This is an RTData issue; NEW trades do actually come in from 4 years ago.
