### ISSUE TITLE
Equity case statement in UPI class

### ISSUE THREAD

**Issue by lmp47** [CSTIB-Hotel/OTCAnalyser#17]
I was trying to get the database to work, and I noticed some problems with the UPI class and the CommunicationLayer class. I think I fixed the CommunicationLayer class so that it only includes Strings that the UPI class will recognise in the case statements, but I'm not sure how taxonomies are meant to be split.

In the UPI class, what was intention in the "Equity" case where the condition taxonomyLength >= 3 is checked and then splitTaxonomy[3] is accessed? Should I check for a length >3 or bump the indices down one?

**Comment by seansaville** [comment]
@sztankatt Can you help with this?

**Comment by sztankatt** [comment]
@lmp47 I have made those if/else statements according to what taxonomies are possible (since the database we are downloading is formatted), according to this: http://www2.isda.org/attachment/NzE5MQ==/ISDA%20OTC%20Derivatives%20Taxonomies%20-%20version%202015-01-09_live.xls

In Equities, if there is a 3rd position in the taxonomy, there will be a 4th one as well, hence the '>=3'. You could change it to '>3' It would not make any difference.

**Comment by sztankatt** [comment]
@lmp47  what part of the database is not working for you? Currently there is a bunch of errors after initalisation, which are not handled, I am working on this. But afaik the database is initialised correctly, only its ommiting a bunch of data.

**Comment by lmp47** [comment]
@sztankatt I haven't identified any problems with the database or the networking part. I have problems with search, though. The CommunicationLayer class was just using strings straight from the GUI taxonomy drop down boxes and putting them (separated by colons) into a single string that it gave to the UPI class as a full taxonomy. As it is now, that means that when you choose "Equity" from the GUI to do a search, it passes a taxonomy with only three positions because there are only three boxes to choose from in the GUI. Actually, this explains why searching the database for certain things might not work, since the CommunicationLayer won't create taxonomies with more than three parts.
If you can give me the correct full taxonomies for the corresponding GUI options (where it is not appropriate just to stick colons between the strings in the boxes), I can try to fix up the CommunicationLayer.

**Comment by sztankatt** [comment]
@lmp47 The taxonomy looks like: AssetClass:SubAssetClass(or base product):SubProduct:TransactionType:SettlementType. 

I Think the UPI should be stored as a separate table in the Database, with the schema (id, tradeid, assetclass, subassetclass, subproduct, transactiontype, settlementtype) then we would be able to perform search at this table, and then lookup the trade id's of all the results.

**Comment by sztankatt** [comment]
@lmp47 @seansaville How about fixing this tomorrow? I really feel that we need the whole group to think about this...

**Comment by seansaville** [comment]
Let's look at this tomorrow (well, today, since I'm writing this at 1.30 in the morning).
