### ISSUE TITLE
NA Taxonomy

### ISSUE THREAD

**Issue by weiszg** [CSTIB-Hotel/OTCAnalyser#18]
I get lots of exceptions when running the app with an empty database - because some Taxonomies are set to NA which it does not recognise. Just out of curiosity: what's going on with the Taxonomies, why is this still a problem? What's wrong with throwing away anything that's not recognised or set it to null?

**Comment by sztankatt** [comment]
Fixed this as well this morning by: ef562f5107dbc452a0330dd2b5b3f79ff825f86c
