### ISSUE TITLE
InvalidTaxonomyException in UPI.java

### ISSUE THREAD

**Issue by waiwaing** [CSTIB-Hotel/OTCAnalyser#2]
In [UPI.java](https://github.com/CSTIB-Hotel/OTCAnalyser/blob/master/OTCAnalyser/src/uk/ac/cam/cstibhotel/otcanalyser/trade/UPI.java#L76), is it intentional that we are catching some InvalidTaxonomyExceptions and throwing others?

**Comment by seansaville** [comment]
The class is broken at the moment, I'm intending to rewrite it tomorrow

**Comment by seansaville** [comment]
I'm closing this now as the fix is contained within my pull request.
