### ISSUE TITLE
compile error (CommunicationLayer.java)

### ISSUE THREAD

**Issue by weiszg** [CSTIB-Hotel/OTCAnalyser#28]
on master, CommunicationLayer.java, line 57, I get this:
The method getText() is undefined for the type JSpinner
can you help me? I have the swingx-0.8.0.jar.

**Comment by seansaville** [comment]
Fixed by e30434d45737ecb73c2f83213aa2031504da3869 as far as I'm aware. Thought I'd already made this change, maybe I didn't commit it by accident. Thanks for pointing it out.
