### ISSUE TITLE
Searching for nonzero maxPrice leads to IllegalArgumentException

### ISSUE THREAD

**Issue by seansaville** [CSTIB-Hotel/OTCAnalyser#39]
Running searches with the default values for minPrice/maxPrice is fine now, I get results and everything is great.

However, change either of these and you get a stack trace looking like this:

> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException
	at uk.ac.cam.cstibhotel.otcanalyser.trade.PriceFormingContinuationData.lookup(PriceFormingContinuationData.java:52)
	at uk.ac.cam.cstibhotel.otcanalyser.database.TradeFieldMapping.makeObjectFromRecord(TradeFieldMapping.java:112)
	at 
uk.ac.cam.cstibhotel.otcanalyser.database.Database.search(Database.java:388)
       at
...

Any ideas why this is? I'm not sure I understand the database well enough to know how to fix this

**Comment by lmp47** [comment]
Maybe this isn't the problem, but did you delete the old database after using the modified PriceFormingContinuationData class?

**Comment by seansaville** [comment]
I've already rebuilt it once and I'm pretty sure I did it after modifying, but I could be wrong so I'll delete it and report back in a bit

**Comment by seansaville** [comment]
Closing because Lauren was right and I'm an idiot
