### ISSUE TITLE
Need UnderLyingAsset field in AnalysisItem

### ISSUE THREAD

**Issue by alistairfisher** [CSTIB-Hotel/OTCAnalyser#40]

**Comment by lmp47** [comment]
Added to dataanalysis branch. It will only be non-null for overall max and min prices because it doesn't really make sense for averages/standard deviations and because I don't know if it's necessary for the monthly max/min data (if you think it is, let me know).

**Comment by alistairfisher** [comment]
No, that's all I need it for
