### ISSUE TITLE
snapshot of broken database

### ISSUE THREAD

**Issue by weiszg** [CSTIB-Hotel/OTCAnalyser#43]
can you just take a brief look at it to confirm the issue is what we think it is (ie slice update starting on exit)

https://www.dropbox.com/s/0s2kwv62okogmj6/database.db_snapshot.zip?dl=0

cheers

**Comment by waiwaing** [comment]
Yes, your analysis is correct. I see

INSERT INTO DATA VALUES(0,0.0E0,'','',NULL,4,'2013-06-13 14:56:52.000000', ...
INSERT INTO DATA VALUES(0,1205.11026E0,'','Gold',NULL,0,'2015-02-26 00:02:02.000000',...
INSERT INTO DATA VALUES(0,1205.37E0,'','Gold',NULL,0,'2015-02-26 00:07:01.000000',...

which very much looks like what you suggest.
