### ISSUE TITLE
UPI class is not working for all the patterns

### ISSUE THREAD

**Issue by sztankatt** [CSTIB-Hotel/OTCAnalyser#6]
The pattern defined in the UPI class for commodities is not always working. Also the Taxonomy is sometimes an empty field, I have introduced a new exception: EmtpyTaxonomyException, which will be thrown when the field is empty.

We should store null in the database upon empty field.

Try running uk.ac.cam.cstibhotel.otcanalyser.networklayer.ParseZIP (with this class as a main entry) in eclipse as it is now, it will access a cummulative_commodities.csv zipped, and output the errors, together with umached patterns.

**Comment by seansaville** [comment]
This is fixed in the branch I'm working on locally. I'll be finishing my work on the communication layer and submitting a pull request tonight :)

**Comment by sztankatt** [comment]
Okay, cool!!


Sent from Samsung Mobile

-------- Original message --------

**Comment by seansaville** [comment]
I'm closing this now, the fix is contained in my pull request.
